# Use the offical node.js 14 image as a base image
FROM node:14

# Set the work dir in the container
WORKDIR /usr/src/app

# Copt the package-lock.json and package.json files in to the container
COPY package.json ./

# Install the application dependencies inside the conatiner
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Specify the command to run when the conatiner starts
CMD ["node","index.js"]